
- name: Create necessary directories
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ cloudfront_repo_build_dir }}"
    - "{{ cloudfront_repo_template_dir }}"

- name: Template CloudFront repo
  template:
    src: "cloudfront.json.j2"
    dest: "{{ playbook_dir }}/{{ cloudfront_repo_template_dir }}/{{ cloudfront_repo_template_name }}"

- name: Create CloudFront repo stack (security token)
  cloudformation:
    region: "{{ cloudfront_repo_region }}"
    stack_name: "{{ cloudfront_repo_stack_name }}"
    state: "{{ cloudfront_stack_state|default('present') }}"
    template: "{{ playbook_dir }}/{{ cloudfront_repo_template_dir }}/{{ cloudfront_repo_template_name }}"
    template_parameters:
      RepositoryName: "{{ cloudfront_repo_name }}"
    tags: "{{ cloudfront_repo_tags }}"
    security_token: "{{ cloudfront_repo_security_token }}"
  when: cloudfront_repo_security_token is defined

- name: Create CloudFront repo stack (no security token)
  cloudformation:
    region: "{{ cloudfront_repo_region }}"
    stack_name: "{{ cloudfront_repo_stack_name }}"
    state: "{{ cloudfront_stack_state|default('present') }}"
    template: "{{ playbook_dir }}/{{ cloudfront_repo_template_dir }}/{{ cloudfront_repo_template_name }}"
    template_parameters:
      RepositoryName: "{{ cloudfront_repo_name }}"
    tags: "{{ cloudfront_repo_tags }}"
  when: cloudfront_repo_security_token is not defined
